import colorama
from colorama import Fore, Back, Style
import random

colorama.init()

strings2Url = 'https://github.com/glmcdona/strings2/raw/master/x64/Release/strings.exe'

prefix = Fore.GREEN + Style.BRIGHT + '[#]' + Fore.WHITE
prefixWarning = Fore.RED + Style.BRIGHT + '[!]' + Fore.WHITE

scanID = "".join(random.choice('ABCDEFGHJKLMNPQRSTUVWXYZ123456789') for i in range(1, 7))

recordingSoftwares = {
    'bdcam.exe':'Bandicam',
    'bandicam.exe':'Bandicam',
    'action.exe':'Mirillis Action',
    'mirillis.exe':'Mirillis Recorder',
    'obs64.exe':'OBS Studio',
    'obs32.exe':'OBS Studio',
    'obs.exe':'OBS Studio',
    'streamlabs.exe':'Streamlabs OBS',
    'streamlabsobs.exe':'Streamlabs OBS',
    'xsplit.core.exe':'XSplit Broadcaster',
    'xsplit.gamecaster.exe':'XSplit Gamecaster',
    'nvidia share.exe':'NVIDIA ShadowPlay',
    'nvcontainer.exe':'NVIDIA ShadowPlay',
    'shadowplay.exe':'NVIDIA ShadowPlay',
    'radeonsoftware.exe':'AMD Radeon ReLive',
    'amddvr.exe':'AMD ReLive',
    'fraps.exe':'Fraps',
    'dxtory.exe':'Dxtory',
    'plays.tv.exe':'Plays.TV',
    'medal.exe':'Medal.tv',
    'medalencoder.exe':'Medal.tv Encoder',
    'lowkey.gg.exe':'Lowkey.gg',
    'gamebar.exe':'Xbox Game Bar',
    'backgroundtaskhost.exe':'Xbox Game DVR',
    'snippingtool.exe':'Windows Snipping Tool',
    'snipandsketch.exe':'Windows Snip & Sketch',
    'sharex.exe':'ShareX',
    'gyazo.exe':'Gyazo',
    'lightshot.exe':'Lightshot',
    'screenrec.exe':'ScreenRec',
    'screencast.exe':'Screencast',
    'screenflow.exe':'ScreenFlow',
    'camtasia.exe':'Camtasia Studio',
    'movavi.screen.recorder.exe':'Movavi Screen Recorder',
    'apowersoft.exe':'Apowersoft Screen Recorder',
    'icecreamscreenrecorder.exe':'Icecream Screen Recorder',
    'loom.exe':'Loom Recorder',
    'flashback.exe':'FlashBack Recorder',
    'debut.exe':'Debut Video Capture',
    'elgato.exe':'Elgato Game Capture',
    'gamecapture.exe':'Elgato Game Capture HD',
    'recentral.exe':'AVerMedia RECentral',
    'avermedia.exe':'AVerMedia Capture',
    'recorder.exe':'Generic Screen Recorder',
    'capture.exe':'Generic Capture Tool',
    'screencapture.exe':'Generic Screen Capture',
    'record.exe':'Generic Recorder',
    'stream.exe':'Generic Streaming Tool',
    'powertoys.exe':'Microsoft PowerToys Recorder',
    'kazam.exe':'Kazam Screencaster',
    'simple.screen.recorder.exe':'SimpleScreenRecorder',
    'vokoscreenNG.exe':'VokoscreenNG',
    'smartpixel.exe':'SmartPixel Recorder',
    'ezvid.exe':'Ezvid Recorder',
    'playsnap.exe':'Playsnap Recorder'
}

dpsStrings = {
    '.exe!2019/03/14:20:01:24':'OP AutoClicker',
    '.exe!2016/05/30:16:33:32':'GS AutoClicker',
    '.exe!2016/04/18:16:56:55':'AutoClicker',
    '.exe!2013/11/26:19:16:05':'MouseClicker',
    '.exe!2018/10/10:19:00:42':'Tap',
    '.exe!2018/10/21:19:34:21':'Ecstasyy',
    '.exe!2018/07/24:11:25:57':'Apollo Lite',
    '.exe!2018/11/09:01:13:38':'GhostBytes',
    '.exe!2019/07/05:07:17:50':'Speed AutoClicker',
    'maxcps':'Generic AutoClicker',
    'mincps':'Generic AutoClicker',
    'clickinterval':'Generic AutoClicker',
    'leftclick':'Generic AutoClicker',
    'rightclick':'Generic AutoClicker'
}

javawStrings = {
    'net/impactclient':'Impact Client',
    '9HzN[Lnet/impactclient/6n;':'Impact Client',
    'SqtkUVg':'Vape v3 #1',
    'CABzZzJ)':'Vape v3 #2',
    'erouax/instavape':'Wax Vape Mod',
    'com/sun/jna/z/a/e/a/a/a/f':'Vape Cracked #1',
    'com/sun/jna/z/Main':'Vape Cracked #2',
    'manthe, aimassist':'Vape Cracked #3',
    'com.sun.jna.zagg':'Vape Cracked #4',
    '2.47-KILL':'Vape Cracked #5',
    'yCcADi':'Vape Cracked #7',
    '>KRTal':'Vape Cracked #8',
    '*YXY*[':'Vape Cracked #9',
    ',#I)!':'Vape Cracked #10 [FORGE ONLY]',
    'kcc((k':'Vape Variation #2',
    'C()[Lf/r;':'Vape Variation #3',
    '(ILjava/lang/Object;[S)V':'Vape Variation #4',
    'hakery.c':'Latemod Injection Client #1',
    'hakery.club':'Latemod Injection Client #2',
    ';9<C7D=CHCAL>@?DQI;MDSQRNQIMKEJ8':'Drip Cracked #1',
    "E-6%%&>6C(\\'<=7BR*$*+*":'Drip Cracked #2',
    '0,$037ADCBDIJICA':'Drip Cracked #3',
    'ZKM9.0.2':'Demon Injection Client #1',
    'Zkh}e':'Demon Injection Client #2',
    '_o&`EGDIk0,AK':'Demon Injection Cracked',
    '| By JensDE':'Labymod v6 Client',
    'me/powns/cheatbreakerhud/settings/ModulesGui.class':'Grim Mod Client #1',
    'io/fishermen/fpsdisplay/settings/Dada.class':'Grim Mod Client #2',
    'fishermen/fpsdisplay/hehe.class':'Grim Mod Client #3',
    'b/mods/combat/':'Grim Mod Client #4',
    'Bruvv.LOL.M':'Grim Mod Client #5',
    'Py3ss 4 k3y':'Grim Mod Client #6',
    'Module3/a':'Grim Mod Client #7',
    '%01%01%01%01%01%01%01%01.class':'Authority Mod Client',
    'net.reach.Verzide':'Verzide Reach Mod #1',
    'net\\reach\\Verzide':'Verzide Reach Mod #2',
    'reach/Verzide':'Verzide Reach Client #3',
    'tsgluke/betterstrafe':'TSGLuke Client #1',
    'me/tsglu/ke':'TSGLuke Client #2',
    'me.tsglu.ke':'TSGLuke Client #3',
    'io.conceal':'Conceal Injection Client',
    'me/tyler/util/CombatUtil.class':'Tyler Client',
    'trumpclientftw_':'Bape Mod Client #1',
    'Bape_g':'Bape Mod Client #2',
    '<>ZRX44':'Trump Client #1',
    'xyz/Incide/gui':'Incide Client',
    '/minecraft/ace/gui/main/category':'Ace Version Client',
    'purgeclient/purgeclientD':'Purge Client #1',
    '\\\\Wbem\\\\wmic.exe':'Purge Client #2',
    'me.veylkar.pepe':'Pepe Mod Client #1',
    'me/veylkar/pepe':'Pepe Mod Client #2',
    'us.cuck.core.':'Cyanide Injection Client #1',
    'us/cuck/core/':'Cyanide Injection Client #2',
    'CyanideButtonUI.java':'Cyanide Injection Client #3',
    'Injected into minecraft enjoy cheating you cuck':'Cyanide Injection Client #4',
    'bspkrs/bspkrscore/fml/UncommonProxy.classUT':'Bspkrscore Mod Client #1',
    'pw/cinque/keystrokesmod/MouseButton$1.class':'KeystrokesMod Cheat #1',
    'keystr0kes':'Raven Mod Client',
    'Minecraft 1.7.10 | R:':'Keystrokes Reach',
    'ping:textures/ping.png':'AntiKB Mod',
    'knockback.setvalue':'AntiKB Mod',
    'velocity/tcpLat':'AntiKB Mod',
    'Lemonade v1.8':'Lemonade Injection Client',
    'kyprak.agent':'Kyprak Injection Client',
    'xyz/gucciclient':'Gucci Mod Client',
    'me/massi/reach':'Massi Reach Mod',
    'DoubleClicker.class':'Double Clicker',
    'AutoClicker.class':'Illegal Modification',
    'KillAura.class':'Illegal Modification',
    'AimAssist.class':'Illegal Modification',
    'ReachMod.class':'Illegal Modification',
    'XRay.class':'Illegal Modification',
    'TriggerBot.class':'Illegal Modification',
    'SelfDestruct.class':'Self Destruct Module',
    'imgui_log.txt':'ImGUI Injection',
    'instrument.dll':'Injection Client',
    'shell.rundll32':'Injection Client',
    'InjectionDLL.dll':'Injection Client',
    'Vape Client V3':'Vape',
    'Iridium Ghost':'Iridium',
    'LiquidBounce':'LiquidBounce Client',
    'Wurst':'Wurst Client',
    'Future Client':'Future Client',
    'Aristois':'Aristois Client',
    'Huzuni':'Huzuni Client',
    'Flux Client':'Flux Client',
    'Sigma':'Sigma Client',
    'Meteor':'Meteor Client',
    'Bleach Client':'Bleach Client',
    'Phantom':'Phantom Client',
    'Xanax':'Xanax Client',
    'Omikron':'Omikron Client',
    'Aperture':'Aperture Client',
    'ZeroDay':'ZeroDay Client',
    'Saint Client':'Saint Client',
    'Ragebot':'Ragebot Client',
    'Skill Client':'Skill Client',
    'Seven Client':'Seven Client',
    'Atom Client':'Atom Client',
    'Paralyzed Client':'Paralyzed Client',
    'Zues Client':'Zues Client',
    'Horizon Client':'Horizon Client',
    'Kryptonite Client':'Kryptonite Client',
    'Wombo Client':'Wombo Client',
    'SNINE Client':'SNINE Client',
    'Best Client':'Best Client',
    'Freestyler Client':'Freestyler Client',
    'Ethylene Client':'Ethylene Client',
    'Gucci Client':'Gucci Client',
    'G Client':'G Client',
    'Vea Client':'Vea Client',
    'Onetap':'Onetap Client',
    'Allatori':'Allatori Obfuscation',
    'SkidProtection':'Skid Obfuscation',
    'Cucklord inside!':'Anti SS Tool'
}